name: Deploy Backend to EC2

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Descargar ultimas imagenes de ECR
            aws ecr get-login-password --region us-east-1 | \
              docker login --username AWS --password-stdin 791990722630.dkr.ecr.us-east-1.amazonaws.com

            docker pull 791990722630.dkr.ecr.us-east-1.amazonaws.com/itpcargo-backend-ventas:latest
            docker pull 791990722630.dkr.ecr.us-east-1.amazonaws.com/itpcargo-backend-despacho:latest

            # Network interna
            docker network create itpcargo-net 2>/dev/null || true

            # Detener contenedores anteriores
            docker stop itpcargo-ventas || true
            docker rm itpcargo-ventas || true
            docker stop itpcargo-despacho || true
            docker rm itpcargo-despacho || true

            # Levantar Ventas (RDS)
            docker run -d \
              --name itpcargo-ventas \
              --restart unless-stopped \
              --network itpcargo-net \
              -p 8080:8080 \
              -e DB_ENDPOINT=itpcargo-db.c1ez2pg4cdse.us-east-1.rds.amazonaws.com \
              -e DB_PORT=3306 \
              -e DB_NAME=itpcargo \
              -e DB_USERNAME=admin \
              -e DB_PASSWORD=itpcargo2025 \
              791990722630.dkr.ecr.us-east-1.amazonaws.com/itpcargo-backend-ventas:latest

            # Levantar Despacho (RDS)
            docker run -d \
              --name itpcargo-despacho \
              --restart unless-stopped \
              --network itpcargo-net \
              -p 8081:8081 \
              -e DB_ENDPOINT=itpcargo-db.c1ez2pg4cdse.us-east-1.rds.amazonaws.com \
              -e DB_PORT=3306 \
              -e DB_NAME=itpcargo \
              -e DB_USERNAME=admin \
              -e DB_PASSWORD=itpcargo2025 \
              791990722630.dkr.ecr.us-east-1.amazonaws.com/itpcargo-backend-despacho:latest

            # Limpiar imagenes antiguas
            docker system prune -f

            echo "Deploy completado"
            docker ps | grep itpcargo
